apiVersion: v1
kind: Service
metadata:
  name: pacman-k8s
spec:
  selector:
    app: pacman-k8s
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman-k8s
  template:
    metadata:
      labels:
        app: pacman-k8s
    spec:
      containers:
        - name: pacman-k8s
          image: hong0163215089/pack8s:de450e1732248eecd140a075a2511b2c7e35cb8c
          #image: us-central1-docker.pkg.dev/core-crossing-400204/pacman/hong0163215089/pack8s:DOCKER_IMG_TAG
    
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27018/pacman
          imagePullPolicy: Always
        

    