substitutions:
  _PROJECT_ID: 'core-crossing-400204'
  _IMAGE_NAME: 'hong0163215089/pack8s'
steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/virtuosity-jk29/Pacman.git', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$IMAGE_NAME:latest', '--no-cache', '-f', 'docker/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$IMAGE_NAME:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/$IMAGE_NAME:latest', 'asia-southeast1-docker.pkg.dev/core-crossing-400204/image/$PROJECT_ID/$IMAGE_NAME:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast1-docker.pkg.dev/core-crossing-400204/image/$PROJECT_ID/$IMAGE_NAME:latest']
