substitutions:
  _PROJECT_ID: 'core-crossing-400204'
  _IMAGE_NAME: 'hong0163215089/pack8s'
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_DOCKER_IMAGE_NAME:latest', '--build-arg', 'SERVICE_ACCOUNT_KEY= ${{ secrets.SERVICE_ACCOUNT_KEY }}', '--no-cache', '-f', 'docker/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/$_DOCKER_IMAGE_NAME:latest', '${{ secrets.DOCKERHUB_USERNAME }}/$_DOCKER_IMAGE_NAME:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${{ secrets.DOCKERHUB_USERNAME }}/$_DOCKER_IMAGE_NAME:latest']
