apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
       - name: MONGO_DB_URL
              value: mongodb://nodeapp-deployment-mongodb:27017/nodeapp-deployment
            - name: PORT
              value: "80"
          image: hong0163215089/pacman-k8s:5
      - name: nodeserver
        image: hong0163215089/pacman-k8s
        ports:
        - containerPort: 8080