version: '3.4'

services:
  app:
    container_name: pacman-mongo
    build: .
    ports:
      - "8000:8080"
    environment:
      MONGODB_URI: mongodb://localhost:27017/pacman-mongo.pacman-result
      JWT_SECRET: secret
    depends_on:
      - mongodb
    restart: unless-stopped

  mongo:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo-data: