version: "3"
services:
  app-k8s:
    build: .
    ports:
      - 8000:80
    image: hong0163215089/pacman-k8s
    environment:  
      PORT: 80
      MONGO_DB_URL: mongodb://mongodb-k8s:27017/app-k8s
    depends_on:
      - mongodb-k8s

  mongodb-k8s:
    image: mongo:3.4
    restart: always
    volumes:
      - mongodb-k8s-volume:/data/db

volumes:
  mongodb-k8s-volume: {}