# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb
# spec:
#   selector:
#     app: mongodb
#   ports:
#     - port: 27017
#       targetPort: 27017

# # ---
# # apiVersion: v1
# # kind: PersistentVolumeClaim
# # metadata:
# #   creationTimestamp: null
# #   name: mongodb-pvc
# # spec:
# #   accessModes:
# #     - ReadWriteOnce
# #   resources:
# #     requests:
# #       storage: 256Mi
# ---
# apiVersion: v1
# kind: Deployment
# metadata: 
#     name: mongodb
# spec:
#     serviceName: mongodb
#     replicas: 1
#     selector: 
#       matchLabels: 
#         app: mongodb
# template: 
#       metadata: 
#         labels: 
#           app: mongodb
# spec: 
#   containers: 
#     - name: mongodb
#       image: mongo:3.4.0
#       imagePullPolicy: "Always"
#   ports: 
#     - containerPort: 27017
#   volumeMounts: 
#     - name: mongodb-data
#       mountPath: "/data/db"
                
# volumes: 
#   - name: mongodb-data
#     persistentVolumeClaim: 
#     claimName: mongodb-pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:3.4.0
          imagePullPolicy: "Always"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc