apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          Volumes:
          - name : mongodb-data
          persistentVolumeClaim:
          claimName : mongodb-data


          

  # apiVersion: "apps/v1"
  # kind: "StatefulSet"
  # metadata: 
  #   name: "mongodb"
  # spec:
  #   serviceName: "mongodb" 
  #   replicas: 1
  #   selector: 
  #     matchLabels: 
  #       app: "mongodb"
  #   template: 
  #     metadata: 
  #       labels: 
  #         app: "mongodb"
  #     spec: 
  #       containers: 
  #         - 
  #           name: "mongodb"
  #           image: "mongo:3.4"
  #           imagePullPolicy: "Always"
  #           ports: 
  #             - 
  #               containerPort: 27017
  #               name: "mongodb"
                
  #           volumeMounts: 
  #             - 
  #               name: "mongodb-persistent-storage"
  #               mountPath: "/data/db"
                
  #       volumes: 
  #         - name: "mongodb-persistent-storage"
  #           persistentVolumeClaim: 
  #             claimName: "mongodb-pvc"


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nodeapp-deployment-mongodb
#   labels:
#     app: nodeapp-mongodb
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nodeapp-mongodb
#   template:
#     metadata:
#       labels:
#         app: nodeapp-mongodb
#     spec:
#       containers:
#       - name: nodeserver-mongodb
#         image: mongo:3.4   # Change the image to MongoDB 3.4
#         ports:
#         - containerPort: 27017   # Change the container port to 27017
