name: Docker build and Deploy

on:
  push:
    branches: [github-gcp]

jobs:
  create-image-and-push-to-dockerhub:
  
    name: Create Image and Push to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: hong0163215089/pack8s:${{ github.sha }}
  
  setup-and-deploy:
    needs: [create-image-and-push-to-dockerhub]

    name: Setup and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: pacman
        location: us-central1-f	

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    
    - name: Pull Latest Docker Image To GKE
      run: |-
          docker push hong0163215089/pack8s:${{ github.sha }}
          docker tag hong0163215089/pack8s:${{ github.sha }} gcr.io/${{ secrets.GKE_PROJECT }}/pack8s:${{ github.sha }}
      # docker pull us-central1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/pacman/${{ secrets.GKE_PROJECT }}/pack8s:${{ github.sha }}
         

    - name: Deploy on the GKE
      run: |-
        sed -i -e 's/DOCKER_IMG_TAG/'${{ github.sha }}'/' app.yaml
        kubectl apply -f app.yaml
