name: Deploy Nodejs

on:
  push:
    branches:
    - 'github-gcp'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hong0163215089/pack8s
      PROJECT_ID: core-crossing-400204

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ env.PROJECT_ID }}
      run: |-
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev
        docker build -t asia-southeast1-docker.pkg.dev/core-crossing-400204/image/$PROJECT_ID/$IMAGE_NAME:latest --no-cache -f docker/Dockerfile  .
        docker push asia-southeast1-docker.pkg.dev/core-crossing-400204/image/$PROJECT_ID/$IMAGE_NAME:latest 
    
    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ env.PROJECT_ID }}
      run: |-
        gcloud container clusters get-credentials pacman-k8s --region adia-east1
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
        kubectl apply -f app.yaml
