name: Docker build and Deploy

on:
  push:
    branches: [github-gcp]

jobs:
  create-image-and-push-to-dockerhub:
  
    name: Create Image and Push to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: hong0163215089/pack8s:${{ github.sha }}
  
  setup-and-deploy:
    needs: [create-image-and-push-to-dockerhub]

    name: Setup and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: pacman
        location: us-central1-f	

    - name: Push Docker Image to Container Registry (GCR)
       run: |-
         docker tag pack8s:DOCKER_IMG_TAG gcr.io/core-crossing-400204/hong0163215089/pack8s:DOCKER_IMG_TAG
         docker push gcr.io/core-crossing-400204/hong0163215089/pack8s:DOCKER_IMG_TAG

     - name: Push Docker Image to Artifact Registry (GAR)
       run: |-
         docker tag pack8s:DOCKER_IMG_TAG us-central1-docker.pkg.dev/core-crossing-400204/pacman/core-crossing-400204/hong0163215089/pack8s:DOCKER_IMG_TAG 
         docker push us-central1-docker.pkg.dev/core-crossing-400204/pacman/core-crossing-400204/hong0163215089/pack8s:DOCKER_IMG_TAG
         
    - name: Deploy on the GKE
      run: |-
        sed -i -e 's/DOCKER_IMG_TAG/'${{ github.sha }}'/' app.yaml
        kubectl apply -f app.yaml

# name: Deploy Nodejs

# on:
#   push:
#     branches:
#     - 'github-gcp'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     env:
#       IMAGE_NAME: hong0163215089/pack8s
#       PROJECT_ID: core-crossing-400204

#     steps:

#     - name: checkout
#       uses: actions/checkout@v2

#     - name: install the gcloud cli
#       uses: google-github-actions/setup-gcloud@v0
#       with:
#         project_id: ${{ env.PROJECT_ID }}
#         service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
#         install_components: 'gke-gcloud-auth-plugin'
#         export_default_credentials: true

#     - name: build and push the docker image
#       env:
#         GOOGLE_PROJECT: ${{ env.PROJECT_ID }}
#       run: |-
#         gcloud auth configure-docker us-central1-docker.pkg.dev
#         docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/pacman/$PROJECT_ID/$IMAGE_NAME:latest --no-cache -f docker/Dockerfile  .
#         docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/pacman/$PROJECT_ID/$IMAGE_NAME:latest 
#     - name: deploy to gke
#       env:
#         GOOGLE_PROJECT: ${{ env.PROJECT_ID }}
#       run: |-
#        gcloud container clusters get-credentials pacman --region us-central1
#         sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" app.yaml
#         kubectl apply -f app.yaml




# -name: Build and Push Image to Google Cloud Platform
# on:
#   push:
#     branches: [ github-gcp ]
# jobs:
#   build-push-gcr:
#     name: Build and Push to GCP
#     runs-on: ubuntu-latest
#     env:
#       IMAGE_NAME: hong0163215089/pack8s
#       PROJECT_ID: core-crossing-400204
      
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - uses: google-github-actions/setup-gcloud@v0
#       with:
#         service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
#         project_id: ${{ env.PROJECT_ID }}
#         export_default_credentials: true

#     - name: Build Docker Image
#       run: docker build . -t $IMAGE_NAME  --no-cache -f docker/Dockerfile 

#     - name: Configure Docker Client
#       run: |-
#         gcloud auth configure-docker --quiet
#         gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

#     - name: Push Docker Image to Container Registry (GCR)
#       run: |-
#         docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest 
#         docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

#     - name: Push Docker Image to Artifact Registry (GAR)
#       run: |-
#         docker tag $IMAGE_NAME:latest asia-southeast1-docker.pkg.dev/core-crossing-400204/image/$PROJECT_ID/$IMAGE_NAME:latest 
#         docker push asia-southeast1-docker.pkg.dev/core-crossing-400204/image/$PROJECT_ID/$IMAGE_NAME:latest