# github actions

name: Dockerhub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   manual way

      - name: Build and push Docker image
        run: |
        
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/pack8s:latest
        
          docker build . -t $IMAGE_TAG  --no-cache -f docker/Dockerfile 
          docker push $IMAGE_TAG