name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ github-gcp ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hong0163215089/pack8s
      PROJECT_ID: core-crossing-400204
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build . -t $IMAGE_NAME  --no-cache -f docker/Dockerfile 

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest 
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

    - name: Push Docker Image to Artifact Registry (GAR)
      run: |-
        docker tag $IMAGE_NAME:latest asia-southeast1-docker.pkg.dev/core-crossing-400204/image/$PROJECT_ID/$IMAGE_NAME:latest 
        docker push asia-southeast1-docker.pkg.dev/core-crossing-400204/image/$PROJECT_ID/$IMAGE_NAME:latest
    
    - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Build and push Docker image
        run: |-
          docker build . -t $IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
