# name: Build Image to Google Cloud

# on: push

# jobs:
#   push_to_registry:
#     name: Push Docker image to Docker Hub
#     runs-on: ubuntu-latest
#     env:
#       IMAGE_NAME: hong0163215089/pack8s
#       PROJECT_ID: core-crossing-400204
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3
      
#       - uses: google-github-actions/setup-gcloud@master
#       with:
#         service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
#         project_id: ${{ env.PROJECT_ID }}
#         export_default_credentials: true

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build Docker image
#         run: |
#           docker build . -t $IMAGE_NAME  --no-cache -f docker/Dockerfile 
        
#       - name: Configure Docker Client
#         run: |-
#         gcloud auth configure-docker --quiet
      
#       - name: Push Docker Image to Container Registry (GCR)
#       run: |-
#         docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
#         docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
       

---
name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ github-gcp ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hong0163215089/pack8s
      PROJECT_ID: core-crossing-400204
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build . -t $IMAGE_NAME  --no-cache -f docker/Dockerfile 

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker Image to Container Registry (GCR)
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest 
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest