# name: Node.js CI/CD

# on: push
# jobs:
#   push_to_registry:
#     name: Push Docker image to Docker Hub
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3
      
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#     #  with library

#       # - name: Build and push Docker image
#       #   uses: docker/build-push-action@v4
#       #   with:
#       #     context: docker/
#       #     push: true
#       #     tags: hong0163215089/pacman-ssh:latest

#     #   manual way


#       - name: Build and push Docker image
#         run: |
#           IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/hong0163215089:${{ github.sha }}
#           docker build -t $IMAGE_TAG ./docker
#           docker push $IMAGE_TAG
        

       
# using self-hosted runner
name: Node.js CI/CD

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub Azure
        uses: docker/login-action@v2
        # azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: | 
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hong0163215089:${{ github.sha }} ./docker
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hong0163215089:${{ github.sha }}
          