name: Node.js CI/CD

on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install --f

    - name: Audit fix dependencies
      run: npm audit fix
    
    - name: Run tests
      run: npm start

    - name: Build
      run: npm run build
