name: Build
on: push

jobs: 

  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
       - name: SonarQube Scan
         uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: ${{ secrets.SONAR_URL }}
