name: SonarQube Scan

on:
  push:
    branches:
      - github-sonarqube

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2  # Use v2 instead of master for the actions/checkout action

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONARQUBE_HOST_URL }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: github-action-sonarqube

# name: SonarQube Code Analysis

# on:
#   push:
#     branches:
#       - github-sonarqube

# jobs:
#   sonarqube-analysis:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
    
#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: 14 
        
#     - name: Install dependencies
#       run: npm install
      
#     - name: SonarQube Scan
#       run: |
#         npm install -g sonarqube-scanner # Install SonarQube Scanner globally
#         sonar-scanner \
#           -Dsonar.host.url=http://localhost:9099 \
#           -Dsonar.projectKey=pacman \
#           -Dsonar.sources=. \
#           -Dsonar.login= $SONAR_TOKEN
#       env:
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
